---
- name: Create users
  hosts: localhost
  tasks:
  - name: include vars
    include_vars:
      dir: vars
  - name: Show vars
    debug:
      msg: "Username: {{db_user}}, {{db_port}}, {{db_pass}}"